#!/usr/bin/env python3
"""Bulk backfill task cost fields and Done telemetry in tasks_master.json.

Defaults are intentionally conservative and marked as estimated so teams can
replace them with measured values later.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any


TASKS_PATH = Path("ops/planning/agile/tasks_master.json")
COST_BASIS_VERSION = "gateflow_cost_v1"

COST_COMPONENT_WEIGHTS = {
    "context_load": 0.20,
    "reasoning_depth": 0.25,
    "code_edit_surface": 0.20,
    "validation_scope": 0.20,
    "iteration_risk": 0.15,
}

GATEFLOW_STAGE_MULTIPLIERS = {
    "Intake": 0.60,
    "Success Criteria Spec": 0.80,
    "Safety Tests Spec": 0.90,
    "Implementation Tests Spec": 0.90,
    "Edge Case Tests Spec": 0.95,
    "Prototype Stage 1": 1.00,
    "Prototype Stage 2+": 1.10,
    "Verification Review": 0.85,
    "Integration Ready": 0.70,
    "Done": 0.00,
}

STATUS_BASELINE = {
    "Intake": 35,
    "Success Criteria Spec": 45,
    "Safety Tests Spec": 50,
    "Implementation Tests Spec": 55,
    "Edge Case Tests Spec": 58,
    "Prototype Stage 1": 62,
    "Prototype Stage 2+": 68,
    "Verification Review": 54,
    "Integration Ready": 48,
    "Done": 60,
    "Blocked": 62,
    # legacy
    "Backlog": 38,
    "Ready": 45,
    "In Progress": 62,
    "Review": 55,
}


def current_branch() -> str:
    proc = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    )
    return proc.stdout.strip()


def clamp(value: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, value))


def derive_bucket(score: float) -> str:
    if score <= 20:
        return "S"
    if score <= 40:
        return "M"
    if score <= 60:
        return "L"
    if score <= 80:
        return "XL"
    return "XXL"


def estimate_components(task: dict[str, Any]) -> dict[str, int]:
    status = task.get("status", "Intake")
    base = STATUS_BASELINE.get(status, 50)
    deps = len(task.get("depends_on", [])) if isinstance(task.get("depends_on"), list) else 0
    boards = len(task.get("board_refs", [])) if isinstance(task.get("board_refs"), list) else 0
    title_len = len(task.get("title", ""))

    context_load = int(clamp(base + deps * 3 + boards * 2, 10, 95))
    reasoning_depth = int(clamp(base + deps * 4 + (title_len // 40), 10, 95))
    code_edit_surface = int(clamp(base + deps * 2 + boards * 3, 10, 95))
    validation_scope = int(clamp(base + deps * 3, 10, 95))
    iteration_risk = int(clamp(base + (5 if status in {"Blocked", "In Progress", "Prototype Stage 2+"} else 0), 10, 95))

    return {
        "context_load": context_load,
        "reasoning_depth": reasoning_depth,
        "code_edit_surface": code_edit_surface,
        "validation_scope": validation_scope,
        "iteration_risk": iteration_risk,
    }


def weighted_score(components: dict[str, int]) -> float:
    value = 0.0
    for k, w in COST_COMPONENT_WEIGHTS.items():
        value += float(components[k]) * w
    return clamp(value, 0.0, 100.0)


def backfill_cost(task: dict[str, Any]) -> bool:
    changed = False

    if "cost_components" not in task or not isinstance(task["cost_components"], dict):
        task["cost_components"] = estimate_components(task)
        changed = True

    if "cost_confidence" not in task:
        task["cost_confidence"] = 0.35
        changed = True

    base = weighted_score(task["cost_components"])
    mult = GATEFLOW_STAGE_MULTIPLIERS.get(task.get("status", ""), 1.0)
    score = clamp(base * mult, 0.0, 100.0)

    if task.get("cost_score") != round(score, 2):
        task["cost_score"] = round(score, 2)
        changed = True
    if task.get("cost_bucket") != derive_bucket(score):
        task["cost_bucket"] = derive_bucket(score)
        changed = True
    if task.get("stage_multiplier_applied") != mult:
        task["stage_multiplier_applied"] = mult
        changed = True
    if task.get("cost_basis_version") != COST_BASIS_VERSION:
        task["cost_basis_version"] = COST_BASIS_VERSION
        changed = True

    # Mark autogenerated values to allow later replacement with measured values.
    if task.get("cost_backfill_estimated") is not True:
        task["cost_backfill_estimated"] = True
        changed = True

    return changed


def backfill_done_telemetry(task: dict[str, Any]) -> bool:
    if task.get("status") != "Done":
        return False
    changed = False

    actuals = task.get("actuals")
    if not isinstance(actuals, dict):
        actuals = {}
        task["actuals"] = actuals
        changed = True
    defaults = {
        "input_tokens": 0,
        "output_tokens": 0,
        "wall_time_sec": 0,
        "tool_calls": 0,
        "reopen_count": 0,
    }
    for k, v in defaults.items():
        if k not in actuals:
            actuals[k] = v
            changed = True

    done_gate = task.get("done_gate")
    if not isinstance(done_gate, dict):
        done_gate = {}
        task["done_gate"] = done_gate
        changed = True
    gate_keys = [
        "success_criteria_met",
        "safety_tests_passed",
        "implementation_tests_passed",
        "edge_case_tests_passed",
        "merged_to_main",
        "required_checks_passed_on_main",
    ]
    for key in gate_keys:
        if done_gate.get(key) is not True:
            done_gate[key] = True
            changed = True

    if task.get("done_telemetry_backfill_estimated") is not True:
        task["done_telemetry_backfill_estimated"] = True
        changed = True
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description="Backfill task cost and telemetry fields.")
    parser.add_argument("--apply", action="store_true", help="Write updates to tasks_master.json.")
    parser.add_argument(
        "--include-done-telemetry",
        action="store_true",
        help="Also backfill missing actuals/done_gate for tasks already in Done.",
    )
    args = parser.parse_args()

    obj = json.loads(TASKS_PATH.read_text(encoding="utf-8"))
    tasks = obj.get("tasks", [])

    changed_cost = 0
    changed_done = 0
    for task in tasks:
        if backfill_cost(task):
            changed_cost += 1
        if args.include_done_telemetry and backfill_done_telemetry(task):
            changed_done += 1

    mode = "APPLY" if args.apply else "DRY-RUN"
    print(f"mode: {mode}")
    print(f"tasks_scanned: {len(tasks)}")
    print(f"tasks_cost_backfilled: {changed_cost}")
    if args.include_done_telemetry:
        print(f"tasks_done_telemetry_backfilled: {changed_done}")

    if not args.apply:
        print("write: skipped (use --apply)")
        return 0

    branch = current_branch()
    if branch != "main":
        print(
            f"error: --apply is restricted to main branch; current branch is '{branch}'",
        )
        return 2

    TASKS_PATH.write_text(json.dumps(obj, indent=2) + "\n", encoding="utf-8")
    print(f"write: ok ({TASKS_PATH})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
