from __future__ import annotations

from pathlib import Path
import os
import runpy
import sys
from types import SimpleNamespace
import unittest


ROOT = Path(__file__).resolve().parents[1]
ANDROID = ROOT / "android"


class AndroidPackagingTests(unittest.TestCase):
    def test_android_project_shape_exists(self) -> None:
        for rel in (
            "settings.gradle.kts",
            "build.gradle.kts",
            "gradle.properties",
            "gradlew",
            "app/build.gradle.kts",
            "app/src/main/AndroidManifest.xml",
            "app/src/main/cpp/luvatrix_camera_preview.frag",
            "app/src/main/cpp/luvatrix_camera_preview_shaders.h",
            "app/src/main/java/com/luvatrix/app/CameraBridge.kt",
            "app/src/main/java/com/luvatrix/app/LuvatrixApplication.kt",
            "app/src/main/java/com/luvatrix/app/MainActivity.kt",
            "app/src/main/java/com/luvatrix/app/StartupResources.kt",
            "app/src/main/python/luvatrix_android_boot.py",
        ):
            self.assertTrue((ANDROID / rel).exists(), rel)

    def test_android_activity_reattaches_and_detaches_process_runtime(self) -> None:
        for root in (ANDROID, ROOT / "luvatrix_core/templates/native/android"):
            activity = (root / "app/src/main/java/com/luvatrix/app/MainActivity.kt").read_text(encoding="utf-8")

            self.assertIn("app.pythonStartup.whenReady(", activity)
            self.assertIn('module.callAttr("run_app_vulkan", luvatrixView)', activity)
            self.assertIn("override fun onDestroy()", activity)
            self.assertIn('module.callAttr("detach_android_view", luvatrixView)', activity)

    def test_android_bootstrap_sources_and_tests_match_native_template(self) -> None:
        template = ROOT / "luvatrix_core/templates/native/android"
        for rel in (
            "app/src/main/AndroidManifest.xml",
            "app/src/main/java/com/luvatrix/app/LaunchPerformance.kt",
            "app/src/main/java/com/luvatrix/app/LuvatrixApplication.kt",
            "app/src/main/java/com/luvatrix/app/MainActivity.kt",
            "app/src/main/java/com/luvatrix/app/NativeVulkan.kt",
            "app/src/main/java/com/luvatrix/app/StartupResources.kt",
            "app/src/test/java/com/luvatrix/app/BootstrapStateTest.kt",
            "app/src/test/java/com/luvatrix/app/LaunchTimelineTest.kt",
        ):
            project_file = ANDROID / rel
            template_file = template / rel
            self.assertTrue(project_file.exists(), rel)
            self.assertTrue(template_file.exists(), rel)
            self.assertEqual(project_file.read_bytes(), template_file.read_bytes(), rel)

        for root in (ANDROID, template):
            bridge = (root / "app/src/main/java/com/luvatrix/app/CameraBridge.kt").read_text(encoding="utf-8")
            view = (root / "app/src/main/java/com/luvatrix/app/LuvatrixVulkanView.kt").read_text(encoding="utf-8")
            self.assertIn("private val cameraManagerDelegate = lazy", bridge)
            self.assertIn("SynchronizedLazyResource { CameraBridge(context) }", view)
            self.assertIn("SceneReplayCoordinator()", view)
            self.assertIn("sceneReplayCoordinator.surfaceAttached(generation)", view)
            self.assertIn("presentNativeSceneLocked(replay)", view)

    def test_android_bootstrap_has_process_scoped_rebindable_presenter(self) -> None:
        for root in (ANDROID, ROOT / "luvatrix_core/templates/native/android"):
            boot = (root / "app/src/main/python/luvatrix_android_boot.py").read_text(encoding="utf-8")

            self.assertIn("class _AndroidViewPresenter", boot)
            self.assertIn("def detach_android_view", boot)
            self.assertIn("_RUNTIME_RUNNING", boot)

    def test_android_template_matches_optimized_python_startup_contract(self) -> None:
        for root in (ANDROID, ROOT / "luvatrix_core/templates/native/android"):
            boot = (root / "app/src/main/python/luvatrix_android_boot.py").read_text(encoding="utf-8")

            self.assertIn('name="luvatrix-android-tls"', boot)
            self.assertIn("before_lifecycle_init=wait_for_tls", boot)
            self.assertIn("defer_hdi_polling_until_first_frame=True", boot)
            self.assertNotIn("def _app_manifest_render_mode", boot)

    def test_android_bootstrap_prefers_chaquopy_bytecode_without_source_wrapper(self) -> None:
        for root in (ANDROID, ROOT / "luvatrix_core/templates/native/android"):
            boot = (root / "app/src/main/python/luvatrix_android_boot.py").read_text(encoding="utf-8")

            self.assertIn("def _materialize_configured_app", boot)
            self.assertIn('joinpath("app_main.pyc").read_bytes()', boot)
            self.assertNotIn("SourcelessFileLoader", boot)

    def test_chaquopy_python_314_is_configured(self) -> None:
        build = (ANDROID / "app" / "build.gradle.kts").read_text(encoding="utf-8")

        self.assertIn("com.chaquo.python", build)
        self.assertIn('version = "3.14"', build)
        self.assertIn("arm64-v8a", build)
        self.assertIn("x86_64", build)
        self.assertIn("JavaVersion.VERSION_17", build)
        self.assertIn("JvmTarget.JVM_17", build)
        self.assertNotIn('install("numpy")', build)
        self.assertNotIn('install("Pillow")', build)
        self.assertIn('install("certifi', build)

    def test_android_template_enables_https_clients(self) -> None:
        for root in (ANDROID, ROOT / "luvatrix_core/templates/native/android"):
            manifest = (root / "app/src/main/AndroidManifest.xml").read_text(encoding="utf-8")
            build = (root / "app/build.gradle.kts").read_text(encoding="utf-8")
            boot = (root / "app/src/main/python/luvatrix_android_boot.py").read_text(encoding="utf-8")

            self.assertIn("android.permission.INTERNET", manifest)
            self.assertIn("android.permission.ACCESS_NETWORK_STATE", manifest)
            self.assertIn('install("certifi', build)
            self.assertIn("def configure_android_tls", boot)

    def test_android_tls_uses_packaged_ca_bundle(self) -> None:
        module = runpy.run_path(str(ANDROID / "app/src/main/python/luvatrix_android_boot.py"))
        previous = sys.modules.get("certifi")
        sys.modules["certifi"] = SimpleNamespace(where=lambda: "/app/cacert.pem")
        old_value = os.environ.get("SSL_CERT_FILE")
        try:
            self.assertEqual(module["configure_android_tls"](), "/app/cacert.pem")
            self.assertEqual(os.environ["SSL_CERT_FILE"], "/app/cacert.pem")
        finally:
            if previous is None:
                sys.modules.pop("certifi", None)
            else:
                sys.modules["certifi"] = previous
            if old_value is None:
                os.environ.pop("SSL_CERT_FILE", None)
            else:
                os.environ["SSL_CERT_FILE"] = old_value

    def test_android_template_exposes_native_rgba_image_loading(self) -> None:
        for root in (ANDROID, ROOT / "luvatrix_core/templates/native/android"):
            view = (root / "app/src/main/java/com/luvatrix/app/LuvatrixVulkanView.kt").read_text(encoding="utf-8")
            boot = (root / "app/src/main/python/luvatrix_android_boot.py").read_text(encoding="utf-8")

            self.assertIn("fun downloadImageRgba", view)
            self.assertIn("BitmapFactory::decodeStream", view)
            self.assertIn("Bitmap.createScaledBitmap", view)
            self.assertIn("def download_image_rgba", boot)

    def test_android_matrix_presentation_disables_bitmap_filtering(self) -> None:
        for root in (ANDROID, ROOT / "luvatrix_core/templates/native/android"):
            view = (root / "app/src/main/java/com/luvatrix/app/LuvatrixVulkanView.kt").read_text(encoding="utf-8")

            self.assertIn("isFilterBitmap = false", view)
            self.assertIn("canvas.drawBitmap(it, null, canvas.clipBounds, matrixPaint)", view)

    def test_android_image_bridge_validates_https_size_and_rgba_length(self) -> None:
        module = runpy.run_path(str(ANDROID / "app/src/main/python/luvatrix_android_boot.py"))

        class View:
            def __init__(self) -> None:
                self.calls: list[tuple[str, int]] = []

            def downloadImageRgba(self, url: str, size: int) -> str:
                import base64

                self.calls.append((url, size))
                return base64.b64encode(bytes(range(size * size * 4))).decode("ascii")

        view = View()
        module["download_image_rgba"].__globals__["_ANDROID_VIEW"] = view
        self.assertEqual(len(module["download_image_rgba"]("https://example.com/avatar.png", 2)), 16)
        self.assertEqual(view.calls, [("https://example.com/avatar.png", 2)])

        with self.assertRaisesRegex(ValueError, "HTTPS"):
            module["download_image_rgba"]("file:///data/local/token", 2)
        with self.assertRaisesRegex(ValueError, "between 1 and 512"):
            module["download_image_rgba"]("https://example.com/avatar.png", 0)

    def test_android_image_bridge_rejects_malformed_native_payload(self) -> None:
        module = runpy.run_path(str(ANDROID / "app/src/main/python/luvatrix_android_boot.py"))

        class View:
            def downloadImageRgba(self, _url: str, _size: int) -> str:
                return "AA=="

        module["download_image_rgba"].__globals__["_ANDROID_VIEW"] = View()
        with self.assertRaisesRegex(RuntimeError, "RGBA"):
            module["download_image_rgba"]("https://example.com/avatar.png", 2)

    def test_emulator_acceptance_script_exists(self) -> None:
        script = ANDROID / "scripts" / "emulator_acceptance.sh"

        self.assertTrue(script.exists())
        self.assertIn("FullSuiteEmulatorAcceptanceTest", script.read_text(encoding="utf-8"))

    def test_matrix_alpha_font_asset_matches_packaged_template(self) -> None:
        project_asset = ANDROID / "app/src/main/assets/luvatrix_matrix_font_alpha.txt"
        template_asset = (
            ROOT
            / "luvatrix_core/templates/native/android/app/src/main/assets/luvatrix_matrix_font_alpha.txt"
        )

        self.assertTrue(project_asset.exists())
        self.assertTrue(template_asset.exists())
        self.assertEqual(project_asset.read_text(encoding="utf-8"), template_asset.read_text(encoding="utf-8"))
        self.assertIn("format=alpha", template_asset.read_text(encoding="utf-8"))

    def test_androidx_is_enabled_for_instrumentation_dependencies(self) -> None:
        props = (ANDROID / "gradle.properties").read_text(encoding="utf-8")

        self.assertIn("android.useAndroidX=true", props)

    def test_android_template_exposes_keystore_secret_storage(self) -> None:
        for root in (ANDROID, ROOT / "luvatrix_core/templates/native/android"):
            view = (root / "app/src/main/java/com/luvatrix/app/LuvatrixVulkanView.kt").read_text(encoding="utf-8")
            boot = (root / "app/src/main/python/luvatrix_android_boot.py").read_text(encoding="utf-8")

            self.assertIn("AndroidKeyStore", view)
            self.assertIn("KeyProperties.BLOCK_MODE_GCM", view)
            self.assertIn("fun writeSecureSecret", view)
            self.assertIn("fun readSecureSecret", view)
            self.assertIn("fun deleteSecureSecret", view)
            self.assertIn("def write_secure_secret", boot)
            self.assertIn("def read_secure_secret", boot)
            self.assertIn("def delete_secure_secret", boot)

    def test_android_secure_storage_python_bridge_round_trips(self) -> None:
        module = runpy.run_path(str(ANDROID / "app/src/main/python/luvatrix_android_boot.py"))

        class View:
            def __init__(self) -> None:
                self.values: dict[str, str] = {}

            def writeSecureSecret(self, key: str, value: str) -> None:
                self.values[key] = value

            def readSecureSecret(self, key: str):
                return self.values.get(key)

            def deleteSecureSecret(self, key: str) -> None:
                self.values.pop(key, None)

        view = View()
        module["write_secure_secret"].__globals__["_ANDROID_VIEW"] = view
        module["write_secure_secret"]("account", "token")
        self.assertEqual(module["read_secure_secret"]("account"), "token")
        module["delete_secure_secret"]("account")
        self.assertIsNone(module["read_secure_secret"]("account"))

    def test_android_secure_storage_writes_fail_when_bridge_is_unavailable(self) -> None:
        module = runpy.run_path(str(ANDROID / "app/src/main/python/luvatrix_android_boot.py"))

        with self.assertRaisesRegex(RuntimeError, "unavailable"):
            module["write_secure_secret"]("account", "token")
        with self.assertRaisesRegex(RuntimeError, "unavailable"):
            module["delete_secure_secret"]("account")

    def test_camera_bridge_declares_camera2_yuv_preview_contract(self) -> None:
        bridge = (ANDROID / "app/src/main/java/com/luvatrix/app/CameraBridge.kt").read_text(encoding="utf-8")
        native = (ANDROID / "app/src/main/java/com/luvatrix/app/NativeVulkan.kt").read_text(encoding="utf-8")
        native_cpp = (ANDROID / "app/src/main/cpp/luvatrix_vulkan_renderer.cpp").read_text(encoding="utf-8")
        shader_source = (ANDROID / "app/src/main/cpp/luvatrix_camera_preview.frag").read_text(encoding="utf-8")
        shader_header = (ANDROID / "app/src/main/cpp/luvatrix_camera_preview_shaders.h").read_text(encoding="utf-8")

        self.assertIn("ImageReader.newInstance", bridge)
        self.assertIn("ImageFormat.YUV_420_888", bridge)
        self.assertIn("ImageFormat.PRIVATE", bridge)
        self.assertIn("HardwareBuffer.USAGE_GPU_SAMPLED_IMAGE", bridge)
        self.assertIn("image.hardwareBuffer", bridge)
        self.assertIn("setCameraFrameHardwareBuffer", bridge)
        self.assertIn("private_preview", bridge)
        self.assertIn("session_targets", bridge)
        self.assertIn("REQUEST_AVAILABLE_CAPABILITIES_RAW", bridge)
        self.assertIn("CameraCapabilityProfile", bridge)
        self.assertIn("capability_profile", bridge)
        self.assertIn("camera.capabilities.raw", bridge)
        self.assertIn("camera.capabilities.private_preview", bridge)
        self.assertIn("REQUEST_MAX_NUM_OUTPUT_STREAMS", bridge)
        self.assertIn("BurstPackageWriter", bridge)
        self.assertIn("burst_manifest.json", bridge)
        self.assertIn("burst_capture", bridge)
        self.assertIn("writeYuvFrame", bridge)
        self.assertIn("captureYuvBurst", bridge)
        self.assertIn("PendingYuvBurst", bridge)
        self.assertIn("writeManifest", bridge)
        self.assertIn("handler.postDelayed", bridge)
        self.assertIn("registerProcessedOutput", bridge)
        self.assertIn("processingTelemetryJson", bridge)
        self.assertIn("processingNativeTiming", bridge)
        self.assertIn("processingSharpnessRejected", bridge)
        self.assertIn("processingExposureRejected", bridge)
        self.assertIn("captureRawBurst", bridge)
        self.assertIn("captureRawComparisonBurst", bridge)
        self.assertIn("pendingRawImagesByTimestamp", bridge)
        self.assertIn("RAW_CAPTURE_TIMEOUT_MS = 12_000L", bridge)
        self.assertIn("RAW_IMAGE_READER_MAX_IMAGES = 8", bridge)
        self.assertIn("SENSOR_TIMESTAMP", bridge)
        self.assertIn('frame_${indexName(index)}.raw16', bridge)
        self.assertIn("raw16_path", bridge)
        self.assertIn("raw16_byte_count", bridge)
        self.assertIn("raw_sharpness_score", bridge)
        self.assertIn("raw_sharpness_method", bridge)
        self.assertIn("bits_per_sample", bridge)
        self.assertIn("black_level_pattern", bridge)
        self.assertIn("white_level", bridge)
        self.assertIn("color_filter_arrangement", bridge)
        self.assertIn("color_correction_gains", bridge)
        self.assertIn("color_correction_transform", bridge)
        self.assertIn("STATISTICS_LENS_SHADING_MAP_MODE", bridge)
        self.assertIn("STATISTICS_LENS_SHADING_CORRECTION_MAP", bridge)
        self.assertIn("lens_shading_available", bridge)
        self.assertIn("lens_shading_map", bridge)
        self.assertIn("lensShadingMapJson", bridge)
        self.assertIn("channel_order", bridge)
        self.assertIn("NativeCameraProcessor", bridge)
        self.assertIn("processYuvBurst", bridge)
        self.assertIn("processRawBurst", bridge)
        self.assertIn("processYuvBurstPackageAsync", bridge)
        self.assertIn("processRawBurstPackageAsync", bridge)
        self.assertIn("processRawComparisonPackageAsync", bridge)
        self.assertIn("RawComparisonVariant", bridge)
        raw_finish = bridge.split("private fun finishRawBurst", 1)[1].split("private fun closePendingRawBurst", 1)[0]
        self.assertIn('status == "saved" || status == "partial"', raw_finish)
        self.assertIn("hasRaw16Frames", raw_finish)
        self.assertLess(raw_finish.find("val manifestFile = pending.writer.writeManifest(manifest)"), raw_finish.find("processRawBurstPackageAsync"))
        self.assertIn("processRawComparisonPackageAsync", raw_finish)
        self.assertIn("downsample_raw_bayer_area", native_cpp)
        self.assertIn("downscale_rgba_bilinear", native_cpp)
        self.assertIn("preview_scale_mode", native_cpp)
        self.assertIn("preview_max_edge > 0", native_cpp)
        self.assertIn("normalized_raw_at_unchecked", native_cpp)
        self.assertIn("RawNormalizeTable", native_cpp)
        self.assertIn("normalized_raw_at_unchecked_fast", native_cpp)
        self.assertIn("render_reduced_bayer_to_rgba_fused", native_cpp)
        self.assertIn("reduced_bayer_rgb_at_direct", native_cpp)
        self.assertIn("reduced_bayer_rgb_at_direct_interior", native_cpp)
        self.assertIn("reduced_bayer_value_at_unchecked", native_cpp)
        self.assertIn("avg2f", native_cpp)
        self.assertIn("avg4f", native_cpp)
        self.assertIn("native_timing_ms", native_cpp)
        self.assertIn("frame_score", native_cpp)
        self.assertIn("selected_load", native_cpp)
        self.assertIn("merge_load", native_cpp)
        self.assertIn("raw_reduce", native_cpp)
        self.assertIn("sharpness_rejected", native_cpp)
        self.assertIn("exposure_rejected", native_cpp)
        self.assertIn("raw_sharpness_compatible", native_cpp)
        self.assertIn("raw_exposure_compatible", native_cpp)
        self.assertIn("sensor_exposure_time_ns", native_cpp)
        self.assertIn("sensor_sensitivity_iso", native_cpp)
        self.assertIn("ae_locked_result", bridge)
        self.assertIn("awb_locked_result", bridge)
        self.assertIn("af_locked_result", bridge)
        self.assertIn("exposureConsistencyJson", bridge)
        self.assertIn("exposure_consistency", bridge)
        self.assertIn("iso_stable", bridge)
        self.assertIn("exposure_time_stable", bridge)
        self.assertIn("Match the output Bayer site parity directly", native_cpp)
        self.assertIn("yy += 2", native_cpp)
        self.assertIn("xx += 2", native_cpp)
        self.assertIn("parallel_for_rows", native_cpp)
        self.assertIn("std::thread::hardware_concurrency", native_cpp)
        self.assertIn("elapsed_ms", native_cpp)
        self.assertIn("IntSpan", native_cpp)
        self.assertIn("raw_green_proxy_fast", native_cpp)
        self.assertIn("raw_sharpness_score", native_cpp)
        self.assertIn("load_selected", native_cpp)
        self.assertIn("build_raw_display_lut", native_cpp)
        self.assertIn("raw_display_byte_lut", native_cpp)
        self.assertIn("bayer_area", native_cpp)
        self.assertIn("reduced_bayer_direct_bilinear", native_cpp)
        self.assertIn("raw_demosaic_mode", bridge)
        self.assertIn("bilinear_fast", native_cpp)
        self.assertIn("malvar_approx", native_cpp)
        self.assertIn("edge_aware_green", native_cpp)
        self.assertIn("setRawDemosaicMode", bridge)
        self.assertIn("fused_rgba", native_cpp)
        self.assertIn("fused_rgba_interior_fast", native_cpp)
        self.assertIn("raw_load_mode", native_cpp)
        self.assertIn("RawProcessingQuality", bridge)
        self.assertIn("fast_1600", bridge)
        self.assertIn("balanced_2400", bridge)
        self.assertIn("full_res", bridge)
        self.assertIn("rawProcessingQualityMode: RawProcessingQuality = RawProcessingQuality.Balanced2400", bridge)
        self.assertIn("rawDemosaicMode: RawDemosaicMode = RawDemosaicMode.MalvarApprox", bridge)
        self.assertIn("rawMergeMode: RawMergeMode = RawMergeMode.AverageMotionAware", bridge)
        self.assertIn("rawRenderStyle: RawRenderStyle = RawRenderStyle.Google", bridge)
        self.assertIn("raw_quality_mode", bridge)
        self.assertIn("render_max_edge", native_cpp)
        self.assertIn("setRawQualityMode", bridge)
        self.assertIn("sharpest_native", bridge)
        self.assertIn("raw_single_frame", bridge)
        self.assertIn("raw_jpeg_export", bridge)
        self.assertIn("raw_gallery_export", bridge)
        self.assertIn("reference_frame", bridge)
        self.assertIn("raw_reference_frame", bridge)
        self.assertIn("used_frames", bridge)
        self.assertIn("rejected_frames", bridge)
        self.assertIn("MediaStore.Images.Media", bridge)
        self.assertIn("RELATIVE_PATH", bridge)
        self.assertIn("Pictures/Luvatrix Camera", bridge)
        self.assertIn("compress(Bitmap.CompressFormat.JPEG", bridge)
        self.assertIn("ExifInterface", bridge)
        self.assertIn("writeProcessedJpegExif", bridge)
        self.assertIn("processedExifMetadata", bridge)
        self.assertIn("applyCaptureExifMetadata", bridge)
        self.assertIn("TAG_DATETIME_ORIGINAL", bridge)
        self.assertIn("TAG_ORIENTATION", bridge)
        self.assertIn("TAG_ISO_SPEED_RATINGS", bridge)
        self.assertIn("TAG_EXPOSURE_TIME", bridge)
        self.assertIn("TAG_F_NUMBER", bridge)
        self.assertIn("TAG_FOCAL_LENGTH", bridge)
        self.assertIn("rotateBitmapForJpeg", bridge)
        self.assertIn("processedJpegRotationDegrees", bridge)
        self.assertIn("output_orientation_degrees", bridge)
        self.assertIn("rawToDisplayRotationDegrees", bridge)
        self.assertIn("RAW_FINAL_JPEG_QUALITY = 96", bridge)
        self.assertIn("PROCESSED_PREVIEW_JPEG_QUALITY = 88", bridge)
        self.assertIn("PROCESSED_PREVIEW_ENABLED = false", bridge)
        self.assertIn("PROCESSED_PREVIEW_MAX_EDGE", bridge)
        self.assertIn("last_gallery_uri", bridge)
        yuv_finish = bridge.split("private fun finishYuvBurst", 1)[1].split("private fun handlePrivateImage", 1)[0]
        self.assertLess(yuv_finish.find("val manifestFile = pending.writer.writeManifest(manifest)"), yuv_finish.find("processYuvBurstPackageAsync"))
        self.assertIn("concurrentCameraIds", bridge)
        self.assertIn("physicalCameraIds", bridge)
        self.assertIn("physical_camera_details", bridge)
        self.assertIn("hidden_camera_probes", bridge)
        self.assertIn("hiddenCameraProbeJson", bridge)
        self.assertIn('"2", "3", "4", "20", "40", "100", "aux", "mono"', bridge)
        self.assertIn("REQUEST_AVAILABLE_CAPABILITIES_MONOCHROME", bridge)
        self.assertIn("SCALER_STREAM_CONFIGURATION_MAP_MAXIMUM_RESOLUTION", bridge)
        self.assertIn("REQUEST_AVAILABLE_CAPABILITIES_ULTRA_HIGH_RESOLUTION_SENSOR", bridge)
        self.assertIn("REQUEST_AVAILABLE_CAPABILITIES_REMOSAIC_REPROCESSING", bridge)
        self.assertIn("getHighResolutionOutputSizes", bridge)
        self.assertIn("SENSOR_INFO_PIXEL_ARRAY_SIZE_MAXIMUM_RESOLUTION", bridge)
        self.assertIn("formatReportsJson", bridge)
        self.assertIn("outputFormats", bridge)
        self.assertIn("availableCaptureRequestKeys", bridge)
        self.assertIn("vendor_key_names", bridge)
        self.assertIn("probe_errors", bridge)
        self.assertIn("probe_summary", bridge)
        self.assertIn("cameraProbeAuditJson", bridge)
        view = (ANDROID / "app/src/main/java/com/luvatrix/app/LuvatrixVulkanView.kt").read_text(encoding="utf-8")
        activity = (ANDROID / "app/src/main/java/com/luvatrix/app/MainActivity.kt").read_text(encoding="utf-8")
        self.assertIn("cameraProbeAuditJson", view)
        self.assertIn("SceneOverlayView", view)
        self.assertIn("overlayView.isClickable = true", view)
        self.assertIn("this@LuvatrixVulkanView.onTouchEvent(event)", view)
        self.assertIn("override fun performClick()", view)
        self.assertIn("preferredDisplayModeId", view)
        self.assertIn("supportedModes", view)
        self.assertIn("setFrameRate", view)
        self.assertIn("CHANGE_FRAME_RATE_ALWAYS", view)
        self.assertIn("displayRefreshTelemetryJson", view)
        self.assertIn("LuvatrixRefreshProbe", view)
        self.assertIn("setRefreshHintMode", view)
        self.assertIn("selected_mode_hz", view)
        self.assertIn("actual_mode_id", view)
        self.assertIn("actual_mode_hz", view)
        self.assertIn("refresh_hint_mode", view)
        self.assertIn("preferred_display_mode_id", view)
        self.assertIn("currentDisplayMode", view)
        self.assertIn("highestDisplayRefreshHz", view)
        self.assertIn("val presentFps = 60", activity)
        self.assertIn("SENSOR_INFO_COLOR_FILTER_ARRANGEMENT", bridge)
        self.assertIn("Bitmap", bridge)
        self.assertIn("Matrix", bridge)
        self.assertIn("Bitmap.CompressFormat.PNG", bridge)
        self.assertIn("CachedPreviewFrame", bridge)
        self.assertIn("latestPreviewFrame", bridge)
        self.assertIn("preview_png_path", bridge)
        self.assertIn("SENSOR_ORIENTATION", bridge)
        self.assertIn("LENS_FOCAL_LENGTH", bridge)
        self.assertIn("LENS_APERTURE", bridge)
        self.assertIn("LENS_FOCUS_DISTANCE", bridge)
        self.assertIn("CONTROL_AE_STATE", bridge)
        self.assertIn("CONTROL_AF_STATE", bridge)
        self.assertIn("CONTROL_AWB_STATE", bridge)
        self.assertIn("CaptureRequest.CONTROL_MODE", bridge)
        self.assertIn("CaptureRequest.SENSOR_SENSITIVITY", bridge)
        self.assertIn("CaptureRequest.SENSOR_EXPOSURE_TIME", bridge)
        self.assertIn("CaptureRequest.LENS_FOCUS_DISTANCE", bridge)
        self.assertIn("CaptureRequest.CONTROL_AF_MODE", bridge)
        self.assertIn("CaptureRequest.CONTROL_AWB_MODE", bridge)
        self.assertIn("CaptureRequest.CONTROL_AWB_MODE_OFF", bridge)
        self.assertIn("setPreviewManualMode", bridge)
        self.assertIn("preview_controls", bridge)
        self.assertIn("updatePreviewResultTelemetry", bridge)
        self.assertIn("setRawCaptureMode", bridge)
        self.assertIn("adjustRawIso", bridge)
        self.assertIn("adjustRawShutter", bridge)
        self.assertIn("adjustRawFocus", bridge)
        self.assertIn("resetRawCaptureControls", bridge)
        self.assertIn('"raw_controls"', bridge)
        self.assertIn("orientation_note", bridge)
        self.assertIn("DngCreator", bridge)
        self.assertIn("captureRawStill", bridge)
        self.assertIn("ImageFormat.RAW_SENSOR", bridge)
        self.assertIn("ImageReader.newInstance(", bridge)
        self.assertIn("RAW_IMAGE_READER_MAX_IMAGES", bridge)
        self.assertIn("session.capture", bridge)
        self.assertIn("RAW_CAPTURE_TIMEOUT_MS", bridge)
        self.assertIn("RAW capture timed out waiting for", bridge)
        self.assertIn("session.stopRepeating", bridge)
        self.assertIn("resumePreviewRepeating", bridge)
        self.assertIn("FileOutputStream", bridge)
        self.assertIn("camera_raw_", bridge)
        self.assertIn('"raw_capture"', bridge)
        self.assertIn("captureRawStill", view)
        self.assertIn("captureYuvBurst", view)
        self.assertIn("setRawCaptureMode", view)
        self.assertIn("setPreviewManualMode", view)
        self.assertIn("setPreviewQualityMode", view)
        self.assertIn("setPreviewTargetMode", view)
        self.assertIn("setPreviewSharpnessMode", view)
        self.assertIn("setPreviewConvolutionLayers", view)
        self.assertIn("setPreviewWhiteBalanceMode", view)
        self.assertIn("setPreviewPipelineMode", view)
        self.assertIn("adjustRawIso", view)
        self.assertIn("resetRawCaptureControls", view)
        self.assertIn("startDualPreview", bridge)
        self.assertIn("setCameraFrameYuv420", native)
        processor = (ANDROID / "app/src/main/java/com/luvatrix/app/NativeCameraProcessor.kt").read_text(encoding="utf-8")
        self.assertIn("object NativeCameraProcessor", processor)
        self.assertIn("processYuvBurst", processor)
        self.assertIn("processRawBurst", processor)
        self.assertIn("setCameraFrameHardwareBuffer", native)
        self.assertIn("clearCameraHardwareBufferSlot", native)
        self.assertIn('NativeVulkan.setCameraCoverMode("pixel_crop")', bridge)
        self.assertIn("setCameraDownsampleMode", native)
        self.assertIn("setCameraConvolutionLayers", native)
        self.assertIn("setCameraColorMode", native)
        self.assertIn("chooseYuvCacheSize", bridge)
        self.assertIn("choosePrivatePreviewCandidates", bridge)
        self.assertIn("orderPrivatePreviewCandidatesForQuality", bridge)
        self.assertIn("PREVIEW_QUALITY_MAX", bridge)
        self.assertIn("PREVIEW_QUALITY_BALANCED", bridge)
        self.assertIn("PREVIEW_QUALITY_FAST", bridge)
        self.assertIn("PREVIEW_TARGET_AUTO", bridge)
        self.assertIn("PREVIEW_TARGET_FULL", bridge)
        self.assertIn("PREVIEW_TARGET_RAW", bridge)
        self.assertIn("PREVIEW_TARGET_SOLO", bridge)
        self.assertIn("setPreviewTargetMode", bridge)
        self.assertIn("PREVIEW_PIPELINE_PREVIEW", bridge)
        self.assertIn("PREVIEW_PIPELINE_RECORD", bridge)
        self.assertIn("PREVIEW_PIPELINE_HQ", bridge)
        self.assertIn("PREVIEW_PIPELINE_RAWISH", bridge)
        self.assertIn("setPreviewPipelineMode", bridge)
        self.assertIn("previewPipelineMode", bridge)
        self.assertIn("private var previewPipelineMode: String = PREVIEW_PIPELINE_HQ", bridge)
        self.assertIn("previewTemplate", bridge)
        self.assertIn("CameraDevice.TEMPLATE_RECORD", bridge)
        self.assertIn("CaptureRequest.EDGE_MODE", bridge)
        self.assertIn("CaptureRequest.EDGE_MODE_HIGH_QUALITY", bridge)
        self.assertIn("CaptureRequest.NOISE_REDUCTION_MODE_HIGH_QUALITY", bridge)
        self.assertIn("CaptureRequest.TONEMAP_MODE_HIGH_QUALITY", bridge)
        self.assertIn("CaptureRequest.COLOR_CORRECTION_ABERRATION_MODE_HIGH_QUALITY", bridge)
        self.assertIn("CaptureRequest.EDGE_MODE_OFF", bridge)
        self.assertIn("CaptureRequest.NOISE_REDUCTION_MODE_OFF", bridge)
        self.assertIn("CaptureRequest.CONTROL_CAPTURE_INTENT_VIDEO_RECORD", bridge)
        self.assertIn("preview_pipeline", bridge)
        self.assertIn("preview_target_mode", bridge)
        self.assertIn("private var previewTargetMode: String = PREVIEW_TARGET_RAW", bridge)
        self.assertIn("if (previewTargetMode == PREVIEW_TARGET_AUTO) PREVIEW_TARGET_RAW else previewTargetMode", bridge)
        self.assertIn("lastGoodPrivateCombo", bridge)
        self.assertIn("last_good_combo", bridge)
        self.assertIn("active_targets", bridge)
        self.assertIn("attempt_index", bridge)
        self.assertIn("attempt_count", bridge)
        self.assertIn("2560", bridge)
        self.assertIn("1920", bridge)
        self.assertIn("getOutputSizes(ImageFormat.PRIVATE)", bridge)
        self.assertIn("privatePreviewCandidates", bridge)
        self.assertIn("candidate_count", bridge)
        self.assertIn("failed_attempts", bridge)
        self.assertIn("includeRawSensor", bridge)
        self.assertIn("schedulePrivateDeliveryWatchdog", bridge)
        self.assertIn("PRIVATE delivery starved", bridge)
        self.assertIn("low_fps_restarts", bridge)
        self.assertIn("acquire_nulls", bridge)
        self.assertIn("images_closed", bridge)
        self.assertIn("native_accepted", bridge)
        self.assertIn("native_rejected", bridge)
        self.assertIn("yuv_cache_width", bridge)
        self.assertIn("privateFpsEstimate", bridge)
        self.assertIn("preview_renderer", native_cpp)
        self.assertIn("preview_gpu_ready", native_cpp)
        self.assertIn("VK_ANDROID_external_memory_android_hardware_buffer", native_cpp)
        self.assertIn("VK_KHR_external_memory", native_cpp)
        self.assertIn("VK_KHR_sampler_ycbcr_conversion", native_cpp)
        self.assertIn("VK_EXT_queue_family_foreign", native_cpp)
        self.assertIn("AHardwareBuffer_fromHardwareBuffer", native_cpp)
        self.assertIn("vkGetAndroidHardwareBufferPropertiesANDROID", native_cpp)
        self.assertIn("VkImportAndroidHardwareBufferInfoANDROID", native_cpp)
        self.assertIn("VkSamplerYcbcrConversionCreateInfo", native_cpp)
        self.assertIn("VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER", native_cpp)
        self.assertIn("vkCreateShaderModule", native_cpp)
        self.assertIn("vkCreateGraphicsPipelines", native_cpp)
        self.assertIn("vkCmdBindDescriptorSets", native_cpp)
        self.assertIn("vkCmdDraw", native_cpp)
        self.assertIn("VK_PIPELINE_BIND_POINT_GRAPHICS", native_cpp)
        self.assertIn("VK_BLEND_FACTOR_SRC_ALPHA", native_cpp)
        self.assertIn("gpu_preview", native_cpp)
        self.assertIn("import_fps", native_cpp)
        self.assertIn("draw_fps", native_cpp)
        self.assertIn("last_draw_ms", native_cpp)
        self.assertIn("last_import_ms", native_cpp)
        self.assertIn("queue_waits", native_cpp)
        self.assertIn("overlay_uploads", native_cpp)
        self.assertIn("overlay_cache_hits", native_cpp)
        self.assertIn("imports_on_render_thread", native_cpp)
        self.assertIn("kMaxImportedCameraPreviewCacheEntries", native_cpp)
        self.assertIn("kMaxImportedCameraPreviewCacheEntries = 12", native_cpp)
        self.assertIn("import_cache_hits", native_cpp)
        self.assertIn("import_cache_misses", native_cpp)
        self.assertIn("import_cache_evictions", native_cpp)
        self.assertIn("last_import_cache_hit", native_cpp)
        self.assertIn("camera_intermediate_render_pass", native_cpp)
        self.assertIn("camera_intermediate_framebuffer", native_cpp)
        self.assertIn("VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT", native_cpp)
        self.assertIn("VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL", native_cpp)
        self.assertIn("intermediate_enabled", native_cpp)
        self.assertIn("intermediate_updates", native_cpp)
        self.assertIn("intermediate_reuses", native_cpp)
        self.assertIn("last_intermediate_ms", native_cpp)
        self.assertIn("intermediate_last_timestamp_ns", native_cpp)
        self.assertIn("intermediate_last_error", native_cpp)
        self.assertIn("downsample_filter", native_cpp)
        self.assertIn("setCameraDownsampleMode", native_cpp)
        self.assertIn("g_downsample_filter", native_cpp)
        self.assertIn('"natural"', native_cpp)
        self.assertIn('"clean"', native_cpp)
        self.assertIn('"lowlight"', native_cpp)
        self.assertIn('"detail"', native_cpp)
        self.assertIn("filter_preset", native_cpp)
        self.assertIn("setCameraConvolutionLayers", native_cpp)
        self.assertIn("convolution_layers", native_cpp)
        self.assertIn("crop_fit_blend", native_cpp)
        self.assertIn('"layer4"', native_cpp)
        self.assertIn("filter_taps", native_cpp)
        self.assertIn("luma_smoothing", native_cpp)
        self.assertIn("g_luma_smoothing", native_cpp)
        self.assertIn("edge_preserve", native_cpp)
        self.assertIn("g_edge_preserve", native_cpp)
        self.assertIn("downsample_taps", native_cpp)
        self.assertIn("downsample_strength", native_cpp)
        self.assertIn("chroma_smoothing", native_cpp)
        self.assertIn("g_chroma_smoothing", native_cpp)
        self.assertIn("last_downsample_ms", native_cpp)
        self.assertIn("last_filter_ms", native_cpp)
        self.assertIn("color_mode", native_cpp)
        self.assertIn("red_gain", native_cpp)
        self.assertIn("green_gain", native_cpp)
        self.assertIn("blue_gain", native_cpp)
        self.assertIn("color_contrast = g_color_contrast", native_cpp)
        self.assertIn("setCameraColorMode", native_cpp)
        self.assertIn('"neutral"', native_cpp)
        self.assertIn('"warm"', native_cpp)
        self.assertIn('"cool"', native_cpp)
        self.assertIn('"natural_plus"', native_cpp)
        self.assertIn('"desk"', native_cpp)
        self.assertIn("downsample_last_error", native_cpp)
        self.assertIn("Preview spatial RGB/chroma convolution shader with GPU contrast", shader_header)
        self.assertIn("layout(push_constant) uniform CameraPush", shader_source)
        self.assertIn("float colorContrast = clamp(pc.tuning.z", shader_source)
        self.assertIn("filteredColor = ((filteredColor - vec3(0.5)) * colorContrast)", shader_source)
        self.assertIn("PreviewFrameSync", native_cpp)
        self.assertIn("kPreviewFramesInFlight = 2", native_cpp)
        self.assertIn("images_in_flight", native_cpp)
        self.assertIn("frames_in_flight", native_cpp)
        self.assertIn("current_frame_slot", native_cpp)
        self.assertIn("image_fence_waits", native_cpp)
        self.assertIn("frame_fence_waits", native_cpp)
        self.assertIn("acquired_image_index", native_cpp)
        self.assertIn("sync_mode", native_cpp)
        self.assertIn("last_used_counter", native_cpp)
        self.assertIn("find_imported_camera_preview_cache_index", native_cpp)
        self.assertIn("evict_imported_camera_preview_if_needed", native_cpp)
        self.assertIn("AHardwareBuffer_acquire(buffer)", native_cpp)
        self.assertIn("AHardwareBuffer_release(entry.buffer)", native_cpp)
        self.assertNotIn("struct GpuPreviewImportCache", native_cpp)
        self.assertIn("frame_sync.image_available", native_cpp)
        self.assertIn("frame_sync.render_finished", native_cpp)
        self.assertIn("frame_sync.in_flight", native_cpp)
        self.assertIn("VkBuffer staging_buffer = VK_NULL_HANDLE;", native_cpp)
        self.assertIn("VkDeviceMemory staging_memory = VK_NULL_HANDLE;", native_cpp)
        self.assertIn("VkDeviceSize staging_capacity = 0;", native_cpp)
        self.assertIn("bool ensure_frame_staging_buffer", native_cpp)
        self.assertIn("ensure_frame_staging_buffer(vk, frame_sync, byte_count)", native_cpp)
        self.assertIn("frame_sync.staging_buffer", native_cpp)
        self.assertIn("vkQueueSubmit(vk.queue, 1, &submit, frame_sync.in_flight)", native_cpp)
        gpu_preview_body = native_cpp.split("bool render_scene_gpu_preview", 1)[1].split("bool render_scene_pixels", 1)[0]
        self.assertNotIn("vkQueueWaitIdle(vk.queue);", gpu_preview_body)
        self.assertNotIn("wait_all_preview_frame_fences", gpu_preview_body)
        scene_pixels_body = native_cpp.split("bool render_scene_pixels", 1)[1].split("bool render_clear", 1)[0]
        self.assertNotIn("vkQueueWaitIdle(vk.queue);", scene_pixels_body)
        clear_body = native_cpp.split("bool render_clear", 1)[1].split("bool render_scene_", 1)[0]
        self.assertNotIn("vkQueueWaitIdle(vk.queue);", clear_body)
        self.assertLess(
            gpu_preview_body.find("vk.camera_intermediate_descriptor_set"),
            gpu_preview_body.find("&vk.overlay_descriptor_set"),
        )
        self.assertIn("monotonic_now_ns", native_cpp)
        self.assertIn("kCameraFragSpv", native_cpp)
        self.assertIn("kOverlayFragSpv", native_cpp)
        self.assertIn("cpu_yuv_bilinear", native_cpp)
        self.assertIn('"pixel_crop"', native_cpp)
        self.assertIn("std::min(out_width, oriented_width)", native_cpp)
        self.assertIn("std::min(static_cast<double>(out_width), static_cast<double>(oriented_width))", native_cpp)
        self.assertIn("plane_value_bilinear", native_cpp)
        self.assertIn("render_camera_preview_pixels", native_cpp)
        self.assertIn("clearCameraFrameSlot", native)
        self.assertIn("cameraTelemetryJson", native)
        self.assertIn("NativeCameraProcessor_processYuvBurst", native_cpp)
        self.assertIn("NativeCameraProcessor_processRawBurst", native_cpp)
        self.assertIn("sharpest_native", native_cpp)
        self.assertIn("raw_single_frame", native_cpp)
        self.assertIn("raw_average_no_alignment", native_cpp)
        self.assertIn("raw_average_motion_aware", native_cpp)
        self.assertIn("raw_average_tile_motion_aware", native_cpp)
        self.assertIn("merge_count", native_cpp)
        self.assertIn("exposure_consistent", native_cpp)
        self.assertIn("motion_rejected_samples", native_cpp)
        self.assertIn("motion_raw_rejected_samples", native_cpp)
        self.assertIn("motion_total_samples", native_cpp)
        self.assertIn("motion_mask_mode", native_cpp)
        self.assertIn("spatial_3x3_min3", native_cpp)
        self.assertIn("stable_mask", native_cpp)
        self.assertIn("raw_merge_mode", bridge)
        self.assertIn("setRawMergeMode", bridge)
        raw_process = bridge.split("private fun processRawBurstPackageAsync", 1)[1].split("private fun processRawComparisonPackageAsync", 1)[0]
        self.assertIn("val mergeMode = RawMergeMode.AverageMotionAware", raw_process)
        self.assertIn("raw_average_global_aligned", native_cpp)
        self.assertIn("alignment_offsets", native_cpp)
        self.assertIn("tile_alignment_grid", native_cpp)
        self.assertIn("tile_alignment_acceptance", native_cpp)
        self.assertIn("conservative_score_0.035", native_cpp)
        self.assertIn("tile_alignment_smoothing", native_cpp)
        self.assertIn("median_3x3", native_cpp)
        self.assertIn("smooth_tile_alignment_offsets_median_3x3", native_cpp)
        self.assertIn("tile_alignment_sampling", native_cpp)
        self.assertIn("bilinear_offset_field", native_cpp)
        self.assertIn("sample_tile_alignment_offset_bilinear", native_cpp)
        self.assertIn("build_tile_alignment_offset_field", native_cpp)
        self.assertIn("tile_alignment_field_cached", native_cpp)
        self.assertIn("tile_alignment_smoothed_count", native_cpp)
        self.assertIn("tile_alignment_offsets", native_cpp)
        self.assertIn("find_reduced_tile_alignment_offset", native_cpp)
        self.assertIn("alignment_failures", native_cpp)
        self.assertIn("green_alignment_proxy", native_cpp)
        self.assertIn("RenderStyleProfile", native_cpp)
        self.assertIn("apply_raw_chroma_guard", native_cpp)
        self.assertIn("chroma_denoise", native_cpp)
        self.assertIn("apply_raw_photo_finishing", native_cpp)
        self.assertIn("raw_photo_finishing", native_cpp)
        self.assertIn("local_contrast", native_cpp)
        self.assertIn("sharpening", native_cpp)
        self.assertIn("RawToneMapTelemetry", native_cpp)
        self.assertIn("tone_map_exposure", native_cpp)
        self.assertIn("tone_map_p95", native_cpp)
        self.assertIn("tone_map_highlight_rolloff", native_cpp)
        self.assertIn("p99_exposure_limit", native_cpp)
        self.assertIn("apply_highlight_color_guard_rgb", native_cpp)
        self.assertIn("normalize_raw_color_transform", native_cpp)
        self.assertIn("normalize_raw_color_gains", native_cpp)
        self.assertIn("green_normalized_clamped_0.55_2.60", native_cpp)
        self.assertIn("apply_raw_radial_chroma_shading_guard", native_cpp)
        self.assertIn("raw_lens_shading_mode", native_cpp)
        self.assertIn("raw_lens_shading_request", native_cpp)
        self.assertIn("lens_shading_mode", native_cpp)
        self.assertIn("sensor_lens_shading_map", native_cpp)
        self.assertIn("raw_lens_shading_map_used", native_cpp)
        self.assertIn("raw_lens_shading_gain_at", native_cpp)
        self.assertIn("lens_shading_usable", native_cpp)
        self.assertIn("raw_quality_verdict_for_artifacts", native_cpp)
        self.assertIn("artifact_guard_single_frame", native_cpp)
        self.assertIn("ratio >= 0.05", native_cpp)
        self.assertIn("ratio >= 0.025", native_cpp)
        self.assertIn("raw_requested_merge_mode", native_cpp)
        self.assertIn("raw_requested_shadow_purple_ratio_after", native_cpp)
        self.assertIn("raw_requested_motion_rejected_ratio", native_cpp)
        self.assertIn("motion_guard_single_frame", native_cpp)
        self.assertIn("requested_motion_rejected_ratio >= 0.18", native_cpp)
        self.assertIn("apply_raw_shadow_purple_guard", native_cpp)
        self.assertIn("raw_artifact_guard", native_cpp)
        self.assertIn("raw_shadow_purple_ratio_before", native_cpp)
        self.assertIn("raw_shadow_purple_ratio_after", native_cpp)
        self.assertIn("raw_color_transform_usable", native_cpp)
        self.assertIn("raw_color_gains_usable", native_cpp)
        self.assertIn("raw_color_matrix_mode", native_cpp)
        self.assertIn("Neutral", native_cpp)
        self.assertIn("Google", native_cpp)
        self.assertIn("Apple", native_cpp)
        self.assertIn("Samsung", native_cpp)
        self.assertIn("Xiaomi", native_cpp)
        self.assertIn("style_profile", native_cpp)
        self.assertIn("shadow_lift", native_cpp)
        self.assertIn("adaptive_shadow_lift", native_cpp)
        self.assertIn("tone_map_shadow_lift", native_cpp)
        self.assertIn("build_raw_display_lut(exposure, style_profile.highlight_rolloff, shadow_lift)", native_cpp)
        self.assertIn("apply_raw_neutral_cast_guard", native_cpp)
        self.assertIn("raw_neutral_cast_guard", native_cpp)
        self.assertIn("gray_world_neutral_v1", native_cpp)
        self.assertIn("raw_neutral_cast_gains", native_cpp)
        self.assertIn("setRawRenderStyle", bridge)
        self.assertIn("processingToneMapExposure", bridge)
        self.assertIn("tone_map_exposure", bridge)
        self.assertIn("processingToneMapShadowLift", bridge)
        self.assertIn("tone_map_shadow_lift", bridge)
        self.assertIn("optFiniteDouble", bridge)
        self.assertIn("processingRawColorGainsUsable", bridge)
        self.assertIn("raw_color_matrix_mode", bridge)
        self.assertIn("raw_color_gain_mode", bridge)
        self.assertIn("raw_lens_shading_mode", bridge)
        self.assertIn("raw_lens_shading_map_used", bridge)
        self.assertIn("raw_requested_merge_mode", bridge)
        self.assertIn("raw_quality_verdict", bridge)
        self.assertIn("raw_quality_fallback", bridge)
        self.assertIn("raw_requested_shadow_purple_ratio_after", bridge)
        self.assertIn("processingRawQualityVerdict", bridge)
        self.assertIn("processingRawQualityFallback", bridge)
        self.assertIn("raw_artifact_guard", bridge)
        self.assertIn("raw_shadow_purple_ratio_before", bridge)
        self.assertIn("RawComparisonVariant(\"neutral\", RawMergeMode.AverageTileMotionAware, RawRenderStyle.Neutral)", bridge)
        self.assertIn("RawComparisonVariant(\"unshaded\", RawMergeMode.AverageMotionAware, lensShadingMode = \"off\")", bridge)
        self.assertIn("RawComparisonVariant(\"radial\", RawMergeMode.AverageMotionAware, lensShadingMode = \"radial\")", bridge)
        self.assertIn("optNullableBoolean", bridge)

        boot = (ANDROID / "app/src/main/python/luvatrix_android_boot.py").read_text(encoding="utf-8")
        self.assertIn("def capture_raw_still", boot)
        self.assertIn("captureRawStill", boot)
        self.assertIn("def capture_yuv_burst", boot)
        self.assertIn("captureYuvBurst", boot)
        self.assertIn("def set_raw_capture_mode", boot)
        self.assertIn("def set_preview_manual_mode", boot)
        self.assertIn("def adjust_raw_iso", boot)
        self.assertIn("def reset_raw_capture_controls", boot)
        self.assertIn("def set_preview_quality_mode", boot)
        self.assertIn("def set_preview_target_mode", boot)
        self.assertIn("def set_preview_sharpness_mode", boot)
        self.assertIn("def set_preview_convolution_layers", boot)
        self.assertIn("def set_preview_white_balance_mode", boot)
        self.assertIn("def set_preview_pipeline_mode", boot)
        self.assertIn("def set_refresh_hint_mode", boot)
        self.assertIn("def process_last_yuv_burst", boot)
        self.assertIn("def process_last_raw_burst", boot)
        self.assertIn("def capture_raw_comparison_burst", boot)
        self.assertIn("def process_last_raw_comparison", boot)


if __name__ == "__main__":
    unittest.main()
