from __future__ import annotations

from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
ANDROID = ROOT / "android"


class AndroidPackagingTests(unittest.TestCase):
    def test_android_project_shape_exists(self) -> None:
        for rel in (
            "settings.gradle.kts",
            "build.gradle.kts",
            "gradle.properties",
            "gradlew",
            "app/build.gradle.kts",
            "app/src/main/AndroidManifest.xml",
            "app/src/main/cpp/luvatrix_camera_preview_shaders.h",
            "app/src/main/java/com/luvatrix/app/CameraBridge.kt",
            "app/src/main/java/com/luvatrix/app/MainActivity.kt",
            "app/src/main/python/luvatrix_android_boot.py",
        ):
            self.assertTrue((ANDROID / rel).exists(), rel)

    def test_chaquopy_python_314_is_configured(self) -> None:
        build = (ANDROID / "app" / "build.gradle.kts").read_text(encoding="utf-8")

        self.assertIn("com.chaquo.python", build)
        self.assertIn('version = "3.14"', build)
        self.assertIn("arm64-v8a", build)
        self.assertIn("x86_64", build)
        self.assertIn("JavaVersion.VERSION_17", build)
        self.assertIn("JvmTarget.JVM_17", build)
        self.assertNotIn('install("numpy")', build)
        self.assertNotIn('install("Pillow")', build)

    def test_emulator_acceptance_script_exists(self) -> None:
        script = ANDROID / "scripts" / "emulator_acceptance.sh"

        self.assertTrue(script.exists())
        self.assertIn("FullSuiteEmulatorAcceptanceTest", script.read_text(encoding="utf-8"))

    def test_androidx_is_enabled_for_instrumentation_dependencies(self) -> None:
        props = (ANDROID / "gradle.properties").read_text(encoding="utf-8")

        self.assertIn("android.useAndroidX=true", props)

    def test_camera_bridge_declares_camera2_yuv_preview_contract(self) -> None:
        bridge = (ANDROID / "app/src/main/java/com/luvatrix/app/CameraBridge.kt").read_text(encoding="utf-8")
        native = (ANDROID / "app/src/main/java/com/luvatrix/app/NativeVulkan.kt").read_text(encoding="utf-8")
        native_cpp = (ANDROID / "app/src/main/cpp/luvatrix_vulkan_renderer.cpp").read_text(encoding="utf-8")
        shader_header = (ANDROID / "app/src/main/cpp/luvatrix_camera_preview_shaders.h").read_text(encoding="utf-8")

        self.assertIn("ImageReader.newInstance", bridge)
        self.assertIn("ImageFormat.YUV_420_888", bridge)
        self.assertIn("ImageFormat.PRIVATE", bridge)
        self.assertIn("HardwareBuffer.USAGE_GPU_SAMPLED_IMAGE", bridge)
        self.assertIn("image.hardwareBuffer", bridge)
        self.assertIn("setCameraFrameHardwareBuffer", bridge)
        self.assertIn("private_preview", bridge)
        self.assertIn("session_targets", bridge)
        self.assertIn("REQUEST_AVAILABLE_CAPABILITIES_RAW", bridge)
        self.assertIn("concurrentCameraIds", bridge)
        self.assertIn("physicalCameraIds", bridge)
        self.assertIn("physical_camera_details", bridge)
        self.assertIn("hidden_camera_probes", bridge)
        self.assertIn("hiddenCameraProbeJson", bridge)
        self.assertIn('"2", "3", "4", "20", "40", "100", "aux", "mono"', bridge)
        self.assertIn("REQUEST_AVAILABLE_CAPABILITIES_MONOCHROME", bridge)
        self.assertIn("SCALER_STREAM_CONFIGURATION_MAP_MAXIMUM_RESOLUTION", bridge)
        self.assertIn("REQUEST_AVAILABLE_CAPABILITIES_ULTRA_HIGH_RESOLUTION_SENSOR", bridge)
        self.assertIn("REQUEST_AVAILABLE_CAPABILITIES_REMOSAIC_REPROCESSING", bridge)
        self.assertIn("getHighResolutionOutputSizes", bridge)
        self.assertIn("SENSOR_INFO_PIXEL_ARRAY_SIZE_MAXIMUM_RESOLUTION", bridge)
        self.assertIn("formatReportsJson", bridge)
        self.assertIn("outputFormats", bridge)
        self.assertIn("availableCaptureRequestKeys", bridge)
        self.assertIn("vendor_key_names", bridge)
        self.assertIn("probe_errors", bridge)
        self.assertIn("probe_summary", bridge)
        self.assertIn("cameraProbeAuditJson", bridge)
        view = (ANDROID / "app/src/main/java/com/luvatrix/app/LuvatrixVulkanView.kt").read_text(encoding="utf-8")
        activity = (ANDROID / "app/src/main/java/com/luvatrix/app/MainActivity.kt").read_text(encoding="utf-8")
        self.assertIn("cameraProbeAuditJson", view)
        self.assertIn("preferredDisplayModeId", view)
        self.assertIn("supportedModes", view)
        self.assertIn("setFrameRate", view)
        self.assertIn("CHANGE_FRAME_RATE_ALWAYS", view)
        self.assertIn("displayRefreshTelemetryJson", view)
        self.assertIn("LuvatrixRefreshProbe", view)
        self.assertIn("setRefreshHintMode", view)
        self.assertIn("selected_mode_hz", view)
        self.assertIn("actual_mode_id", view)
        self.assertIn("actual_mode_hz", view)
        self.assertIn("refresh_hint_mode", view)
        self.assertIn("preferred_display_mode_id", view)
        self.assertIn("currentDisplayMode", view)
        self.assertIn("highestDisplayRefreshHz", view)
        self.assertIn("val presentFps = 60", activity)
        self.assertIn("SENSOR_INFO_COLOR_FILTER_ARRANGEMENT", bridge)
        self.assertIn("Bitmap", bridge)
        self.assertIn("Matrix", bridge)
        self.assertIn("Bitmap.CompressFormat.PNG", bridge)
        self.assertIn("CachedPreviewFrame", bridge)
        self.assertIn("latestPreviewFrame", bridge)
        self.assertIn("preview_png_path", bridge)
        self.assertIn("SENSOR_ORIENTATION", bridge)
        self.assertIn("LENS_FOCAL_LENGTH", bridge)
        self.assertIn("LENS_APERTURE", bridge)
        self.assertIn("LENS_FOCUS_DISTANCE", bridge)
        self.assertIn("CONTROL_AE_STATE", bridge)
        self.assertIn("CONTROL_AF_STATE", bridge)
        self.assertIn("CONTROL_AWB_STATE", bridge)
        self.assertIn("CaptureRequest.CONTROL_MODE", bridge)
        self.assertIn("CaptureRequest.SENSOR_SENSITIVITY", bridge)
        self.assertIn("CaptureRequest.SENSOR_EXPOSURE_TIME", bridge)
        self.assertIn("CaptureRequest.LENS_FOCUS_DISTANCE", bridge)
        self.assertIn("CaptureRequest.CONTROL_AF_MODE", bridge)
        self.assertIn("CaptureRequest.CONTROL_AWB_MODE", bridge)
        self.assertIn("CaptureRequest.CONTROL_AWB_MODE_OFF", bridge)
        self.assertIn("setPreviewManualMode", bridge)
        self.assertIn("preview_controls", bridge)
        self.assertIn("updatePreviewResultTelemetry", bridge)
        self.assertIn("setRawCaptureMode", bridge)
        self.assertIn("adjustRawIso", bridge)
        self.assertIn("adjustRawShutter", bridge)
        self.assertIn("adjustRawFocus", bridge)
        self.assertIn("resetRawCaptureControls", bridge)
        self.assertIn('"raw_controls"', bridge)
        self.assertIn("orientation_note", bridge)
        self.assertIn("DngCreator", bridge)
        self.assertIn("captureRawStill", bridge)
        self.assertIn("ImageFormat.RAW_SENSOR", bridge)
        self.assertIn("ImageReader.newInstance(rawSize.width, rawSize.height, ImageFormat.RAW_SENSOR", bridge)
        self.assertIn("session.capture", bridge)
        self.assertIn("RAW_CAPTURE_TIMEOUT_MS", bridge)
        self.assertIn("RAW capture timed out waiting for", bridge)
        self.assertIn("session.stopRepeating", bridge)
        self.assertIn("resumePreviewRepeating", bridge)
        self.assertIn("FileOutputStream", bridge)
        self.assertIn("camera_raw_", bridge)
        self.assertIn('"raw_capture"', bridge)
        self.assertIn("captureRawStill", view)
        self.assertIn("setRawCaptureMode", view)
        self.assertIn("setPreviewManualMode", view)
        self.assertIn("setPreviewQualityMode", view)
        self.assertIn("setPreviewTargetMode", view)
        self.assertIn("setPreviewSharpnessMode", view)
        self.assertIn("setPreviewConvolutionLayers", view)
        self.assertIn("setPreviewWhiteBalanceMode", view)
        self.assertIn("setPreviewPipelineMode", view)
        self.assertIn("adjustRawIso", view)
        self.assertIn("resetRawCaptureControls", view)
        self.assertIn("startDualPreview", bridge)
        self.assertIn("setCameraFrameYuv420", native)
        self.assertIn("setCameraFrameHardwareBuffer", native)
        self.assertIn("clearCameraHardwareBufferSlot", native)
        self.assertIn('NativeVulkan.setCameraCoverMode("pixel_crop")', bridge)
        self.assertIn("setCameraDownsampleMode", native)
        self.assertIn("setCameraConvolutionLayers", native)
        self.assertIn("setCameraColorMode", native)
        self.assertIn("chooseYuvCacheSize", bridge)
        self.assertIn("choosePrivatePreviewCandidates", bridge)
        self.assertIn("orderPrivatePreviewCandidatesForQuality", bridge)
        self.assertIn("PREVIEW_QUALITY_MAX", bridge)
        self.assertIn("PREVIEW_QUALITY_BALANCED", bridge)
        self.assertIn("PREVIEW_QUALITY_FAST", bridge)
        self.assertIn("PREVIEW_TARGET_AUTO", bridge)
        self.assertIn("PREVIEW_TARGET_FULL", bridge)
        self.assertIn("PREVIEW_TARGET_RAW", bridge)
        self.assertIn("PREVIEW_TARGET_SOLO", bridge)
        self.assertIn("setPreviewTargetMode", bridge)
        self.assertIn("PREVIEW_PIPELINE_PREVIEW", bridge)
        self.assertIn("PREVIEW_PIPELINE_RECORD", bridge)
        self.assertIn("PREVIEW_PIPELINE_HQ", bridge)
        self.assertIn("PREVIEW_PIPELINE_RAWISH", bridge)
        self.assertIn("setPreviewPipelineMode", bridge)
        self.assertIn("previewPipelineMode", bridge)
        self.assertIn("private var previewPipelineMode: String = PREVIEW_PIPELINE_HQ", bridge)
        self.assertIn("previewTemplate", bridge)
        self.assertIn("CameraDevice.TEMPLATE_RECORD", bridge)
        self.assertIn("CaptureRequest.EDGE_MODE", bridge)
        self.assertIn("CaptureRequest.EDGE_MODE_HIGH_QUALITY", bridge)
        self.assertIn("CaptureRequest.NOISE_REDUCTION_MODE_HIGH_QUALITY", bridge)
        self.assertIn("CaptureRequest.TONEMAP_MODE_HIGH_QUALITY", bridge)
        self.assertIn("CaptureRequest.COLOR_CORRECTION_ABERRATION_MODE_HIGH_QUALITY", bridge)
        self.assertIn("CaptureRequest.EDGE_MODE_OFF", bridge)
        self.assertIn("CaptureRequest.NOISE_REDUCTION_MODE_OFF", bridge)
        self.assertIn("CaptureRequest.CONTROL_CAPTURE_INTENT_VIDEO_RECORD", bridge)
        self.assertIn("preview_pipeline", bridge)
        self.assertIn("preview_target_mode", bridge)
        self.assertIn("private var previewTargetMode: String = PREVIEW_TARGET_RAW", bridge)
        self.assertIn("if (previewTargetMode == PREVIEW_TARGET_AUTO) PREVIEW_TARGET_RAW else previewTargetMode", bridge)
        self.assertIn("lastGoodPrivateCombo", bridge)
        self.assertIn("last_good_combo", bridge)
        self.assertIn("active_targets", bridge)
        self.assertIn("attempt_index", bridge)
        self.assertIn("attempt_count", bridge)
        self.assertIn("2560", bridge)
        self.assertIn("1920", bridge)
        self.assertIn("getOutputSizes(ImageFormat.PRIVATE)", bridge)
        self.assertIn("privatePreviewCandidates", bridge)
        self.assertIn("candidate_count", bridge)
        self.assertIn("failed_attempts", bridge)
        self.assertIn("includeRawSensor", bridge)
        self.assertIn("schedulePrivateDeliveryWatchdog", bridge)
        self.assertIn("PRIVATE delivery starved", bridge)
        self.assertIn("low_fps_restarts", bridge)
        self.assertIn("acquire_nulls", bridge)
        self.assertIn("images_closed", bridge)
        self.assertIn("native_accepted", bridge)
        self.assertIn("native_rejected", bridge)
        self.assertIn("yuv_cache_width", bridge)
        self.assertIn("privateFpsEstimate", bridge)
        self.assertIn("preview_renderer", native_cpp)
        self.assertIn("preview_gpu_ready", native_cpp)
        self.assertIn("VK_ANDROID_external_memory_android_hardware_buffer", native_cpp)
        self.assertIn("VK_KHR_external_memory", native_cpp)
        self.assertIn("VK_KHR_sampler_ycbcr_conversion", native_cpp)
        self.assertIn("VK_EXT_queue_family_foreign", native_cpp)
        self.assertIn("AHardwareBuffer_fromHardwareBuffer", native_cpp)
        self.assertIn("vkGetAndroidHardwareBufferPropertiesANDROID", native_cpp)
        self.assertIn("VkImportAndroidHardwareBufferInfoANDROID", native_cpp)
        self.assertIn("VkSamplerYcbcrConversionCreateInfo", native_cpp)
        self.assertIn("VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER", native_cpp)
        self.assertIn("vkCreateShaderModule", native_cpp)
        self.assertIn("vkCreateGraphicsPipelines", native_cpp)
        self.assertIn("vkCmdBindDescriptorSets", native_cpp)
        self.assertIn("vkCmdDraw", native_cpp)
        self.assertIn("VK_PIPELINE_BIND_POINT_GRAPHICS", native_cpp)
        self.assertIn("VK_BLEND_FACTOR_SRC_ALPHA", native_cpp)
        self.assertIn("gpu_preview", native_cpp)
        self.assertIn("import_fps", native_cpp)
        self.assertIn("draw_fps", native_cpp)
        self.assertIn("last_draw_ms", native_cpp)
        self.assertIn("last_import_ms", native_cpp)
        self.assertIn("queue_waits", native_cpp)
        self.assertIn("overlay_uploads", native_cpp)
        self.assertIn("overlay_cache_hits", native_cpp)
        self.assertIn("imports_on_render_thread", native_cpp)
        self.assertIn("kMaxImportedCameraPreviewCacheEntries", native_cpp)
        self.assertIn("kMaxImportedCameraPreviewCacheEntries = 12", native_cpp)
        self.assertIn("import_cache_hits", native_cpp)
        self.assertIn("import_cache_misses", native_cpp)
        self.assertIn("import_cache_evictions", native_cpp)
        self.assertIn("last_import_cache_hit", native_cpp)
        self.assertIn("camera_intermediate_render_pass", native_cpp)
        self.assertIn("camera_intermediate_framebuffer", native_cpp)
        self.assertIn("VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT", native_cpp)
        self.assertIn("VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL", native_cpp)
        self.assertIn("intermediate_enabled", native_cpp)
        self.assertIn("intermediate_updates", native_cpp)
        self.assertIn("intermediate_reuses", native_cpp)
        self.assertIn("last_intermediate_ms", native_cpp)
        self.assertIn("intermediate_last_timestamp_ns", native_cpp)
        self.assertIn("intermediate_last_error", native_cpp)
        self.assertIn("downsample_filter", native_cpp)
        self.assertIn("setCameraDownsampleMode", native_cpp)
        self.assertIn("g_downsample_filter", native_cpp)
        self.assertIn('"natural"', native_cpp)
        self.assertIn('"clean"', native_cpp)
        self.assertIn('"lowlight"', native_cpp)
        self.assertIn('"detail"', native_cpp)
        self.assertIn("filter_preset", native_cpp)
        self.assertIn("setCameraConvolutionLayers", native_cpp)
        self.assertIn("convolution_layers", native_cpp)
        self.assertIn("crop_fit_blend", native_cpp)
        self.assertIn('"layer4"', native_cpp)
        self.assertIn("filter_taps", native_cpp)
        self.assertIn("luma_smoothing", native_cpp)
        self.assertIn("g_luma_smoothing", native_cpp)
        self.assertIn("edge_preserve", native_cpp)
        self.assertIn("g_edge_preserve", native_cpp)
        self.assertIn("downsample_taps", native_cpp)
        self.assertIn("downsample_strength", native_cpp)
        self.assertIn("chroma_smoothing", native_cpp)
        self.assertIn("g_chroma_smoothing", native_cpp)
        self.assertIn("last_downsample_ms", native_cpp)
        self.assertIn("last_filter_ms", native_cpp)
        self.assertIn("color_mode", native_cpp)
        self.assertIn("red_gain", native_cpp)
        self.assertIn("green_gain", native_cpp)
        self.assertIn("blue_gain", native_cpp)
        self.assertIn("setCameraColorMode", native_cpp)
        self.assertIn('"neutral"', native_cpp)
        self.assertIn('"warm"', native_cpp)
        self.assertIn('"cool"', native_cpp)
        self.assertIn('"desk"', native_cpp)
        self.assertIn("downsample_last_error", native_cpp)
        self.assertIn("Preview spatial RGB/chroma convolution shader", shader_header)
        self.assertIn("PreviewFrameSync", native_cpp)
        self.assertIn("kPreviewFramesInFlight = 2", native_cpp)
        self.assertIn("images_in_flight", native_cpp)
        self.assertIn("frames_in_flight", native_cpp)
        self.assertIn("current_frame_slot", native_cpp)
        self.assertIn("image_fence_waits", native_cpp)
        self.assertIn("frame_fence_waits", native_cpp)
        self.assertIn("acquired_image_index", native_cpp)
        self.assertIn("sync_mode", native_cpp)
        self.assertIn("last_used_counter", native_cpp)
        self.assertIn("find_imported_camera_preview_cache_index", native_cpp)
        self.assertIn("evict_imported_camera_preview_if_needed", native_cpp)
        self.assertIn("AHardwareBuffer_acquire(buffer)", native_cpp)
        self.assertIn("AHardwareBuffer_release(entry.buffer)", native_cpp)
        self.assertNotIn("struct GpuPreviewImportCache", native_cpp)
        self.assertIn("frame_sync.image_available", native_cpp)
        self.assertIn("frame_sync.render_finished", native_cpp)
        self.assertIn("frame_sync.in_flight", native_cpp)
        self.assertIn("vkQueueSubmit(vk.queue, 1, &submit, frame_sync.in_flight)", native_cpp)
        gpu_preview_body = native_cpp.split("bool render_scene_gpu_preview", 1)[1].split("bool render_scene_pixels", 1)[0]
        self.assertNotIn("vkQueueWaitIdle(vk.queue);", gpu_preview_body)
        self.assertNotIn("wait_all_preview_frame_fences", gpu_preview_body)
        self.assertLess(
            gpu_preview_body.find("vk.camera_intermediate_descriptor_set"),
            gpu_preview_body.find("&vk.overlay_descriptor_set"),
        )
        self.assertIn("monotonic_now_ns", native_cpp)
        self.assertIn("kCameraFragSpv", native_cpp)
        self.assertIn("kOverlayFragSpv", native_cpp)
        self.assertIn("cpu_yuv_bilinear", native_cpp)
        self.assertIn('"pixel_crop"', native_cpp)
        self.assertIn("std::min(out_width, oriented_width)", native_cpp)
        self.assertIn("std::min(static_cast<double>(out_width), static_cast<double>(oriented_width))", native_cpp)
        self.assertIn("plane_value_bilinear", native_cpp)
        self.assertIn("render_camera_preview_pixels", native_cpp)
        self.assertIn("clearCameraFrameSlot", native)
        self.assertIn("cameraTelemetryJson", native)

        boot = (ANDROID / "app/src/main/python/luvatrix_android_boot.py").read_text(encoding="utf-8")
        self.assertIn("def capture_raw_still", boot)
        self.assertIn("captureRawStill", boot)
        self.assertIn("def set_raw_capture_mode", boot)
        self.assertIn("def set_preview_manual_mode", boot)
        self.assertIn("def adjust_raw_iso", boot)
        self.assertIn("def reset_raw_capture_controls", boot)
        self.assertIn("def set_preview_quality_mode", boot)
        self.assertIn("def set_preview_target_mode", boot)
        self.assertIn("def set_preview_sharpness_mode", boot)
        self.assertIn("def set_preview_convolution_layers", boot)
        self.assertIn("def set_preview_white_balance_mode", boot)
        self.assertIn("def set_preview_pipeline_mode", boot)
        self.assertIn("def set_refresh_hint_mode", boot)


if __name__ == "__main__":
    unittest.main()
