from .audit import JsonlAuditSink, SQLiteAuditSink
from .app_runtime import (
    APP_PROTOCOL_VERSION,
    AppContext,
    AppLifecycle,
    AppManifest,
    AppRuntime,
    AppUIRenderer,
    AppVariant,
    ResolvedAppVariant,
)
from .display_runtime import DisplayRuntime, RenderTick
from .debug_menu import (
    DEFAULT_DEBUG_MENU_ACTIONS,
    DebugMenuAdapterSpec,
    DebugMenuActionSpec,
    DebugMenuDispatchResult,
    DebugMenuDispatcher,
    build_debug_capability_registry,
    debug_menu_adapter_capability_matrix,
    default_debug_menu_adapter_specs,
    validate_debug_menu_actions,
)
from .debug_capture import (
    OverlayRect,
    OverlaySpec,
    OverlayToggleResult,
    REQUIRED_SCREENSHOT_SIDECAR_KEYS,
    REQUIRED_RECORDING_MANIFEST_KEYS,
    DebugCapturePlatformSpec,
    RecordingBudgetEnvelope,
    RecordingBudgetResult,
    ScreenshotArtifactBundle,
    build_recording_manifest,
    build_screenshot_artifact_bundle,
    build_screenshot_sidecar,
    debug_capture_platform_capability_matrix,
    build_overlay_spec,
    evaluate_recording_budget,
    default_debug_capture_platform_specs,
    screenshot_artifacts_are_atomic,
    toggle_overlay_non_destructive,
    validate_overlay_spec,
)
from .frame_rate_controller import FrameRateController
from .ui_frame_renderer import MatrixUIFrameRenderer
from .coordinates import (
    CoordinateFrame,
    CoordinateFrameRegistry,
    PRESET_CARTESIAN_BL,
    PRESET_CARTESIAN_CENTER,
    PRESET_SCREEN_TL,
)
from .energy_safety import EnergySafetyController, EnergySafetyDecision, EnergySafetyPolicy, SensorEnergySafetyController
from .engine import Engine
from .hdi_thread import HDIEvent, HDIEventSource, HDIThread
from .events import InputEvent
from .protocol_governance import (
    CURRENT_PROTOCOL_VERSION,
    DEPRECATED_PROTOCOL_VERSIONS,
    SUPPORTED_PROTOCOL_VERSIONS,
    ProtocolCompatibility,
    check_protocol_compatibility,
)
from .sensor_manager import (
    DEFAULT_ENABLED_SENSORS,
    FallbackSensorProvider,
    SensorReadDeniedError,
    SensorReadUnavailableError,
    SensorManagerThread,
    SensorProvider,
    SensorSample,
    TTLCachedSensorProvider,
)
from .unified_runtime import UnifiedRunResult, UnifiedRuntime
from .window_matrix import (
    CallBlitEvent,
    FullRewrite,
    Multiply,
    PushColumn,
    PushRow,
    ShiftFrame,
    ReplaceRect,
    ReplaceColumn,
    ReplaceRow,
    WriteBatch,
    WindowMatrix,
)

__all__ = [
    "CallBlitEvent",
    "APP_PROTOCOL_VERSION",
    "AppContext",
    "AppLifecycle",
    "AppManifest",
    "AppRuntime",
    "AppUIRenderer",
    "AppVariant",
    "ResolvedAppVariant",
    "JsonlAuditSink",
    "DisplayRuntime",
    "DebugMenuDispatchResult",
    "DebugMenuDispatcher",
    "DebugMenuActionSpec",
    "DebugMenuAdapterSpec",
    "DebugCapturePlatformSpec",
    "RecordingBudgetEnvelope",
    "RecordingBudgetResult",
    "OverlayRect",
    "OverlaySpec",
    "OverlayToggleResult",
    "ScreenshotArtifactBundle",
    "DEFAULT_DEBUG_MENU_ACTIONS",
    "REQUIRED_RECORDING_MANIFEST_KEYS",
    "REQUIRED_SCREENSHOT_SIDECAR_KEYS",
    "build_recording_manifest",
    "build_overlay_spec",
    "build_screenshot_artifact_bundle",
    "build_screenshot_sidecar",
    "validate_overlay_spec",
    "evaluate_recording_budget",
    "toggle_overlay_non_destructive",
    "screenshot_artifacts_are_atomic",
    "default_debug_capture_platform_specs",
    "debug_capture_platform_capability_matrix",
    "build_debug_capability_registry",
    "default_debug_menu_adapter_specs",
    "debug_menu_adapter_capability_matrix",
    "validate_debug_menu_actions",
    "FrameRateController",
    "Engine",
    "FullRewrite",
    "HDIEvent",
    "HDIEventSource",
    "HDIThread",
    "InputEvent",
    "Multiply",
    "PushColumn",
    "PushRow",
    "ShiftFrame",
    "ReplaceRect",
    "ReplaceColumn",
    "ReplaceRow",
    "RenderTick",
    "MatrixUIFrameRenderer",
    "CoordinateFrame",
    "CoordinateFrameRegistry",
    "PRESET_SCREEN_TL",
    "PRESET_CARTESIAN_BL",
    "PRESET_CARTESIAN_CENTER",
    "EnergySafetyController",
    "EnergySafetyDecision",
    "EnergySafetyPolicy",
    "SensorEnergySafetyController",
    "DEFAULT_ENABLED_SENSORS",
    "CURRENT_PROTOCOL_VERSION",
    "DEPRECATED_PROTOCOL_VERSIONS",
    "SUPPORTED_PROTOCOL_VERSIONS",
    "ProtocolCompatibility",
    "check_protocol_compatibility",
    "FallbackSensorProvider",
    "SensorReadDeniedError",
    "SensorReadUnavailableError",
    "SensorManagerThread",
    "SensorProvider",
    "SensorSample",
    "TTLCachedSensorProvider",
    "SQLiteAuditSink",
    "UnifiedRunResult",
    "UnifiedRuntime",
    "WriteBatch",
    "WindowMatrix",
]
