__all__ = [
    "CallBlitEvent",
    "APP_PROTOCOL_VERSION",
    "AppDebugPolicy",
    "AppContext",
    "AppLifecycle",
    "AppManifest",
    "AppRuntime",
    "AppUIRenderer",
    "AppVariant",
    "ResolvedAppVariant",
    "JsonlAuditSink",
    "DisplayRuntime",
    "DebugMenuDispatchResult",
    "DebugMenuDispatcher",
    "DebugMenuActionSpec",
    "DebugMenuAdapterSpec",
    "DebugCapturePlatformSpec",
    "RecordingBudgetEnvelope",
    "RecordingBudgetResult",
    "OverlayRect",
    "OverlaySpec",
    "OverlayToggleResult",
    "ScreenshotArtifactBundle",
    "DEFAULT_DEBUG_MENU_ACTIONS",
    "REQUIRED_RECORDING_MANIFEST_KEYS",
    "REQUIRED_SCREENSHOT_SIDECAR_KEYS",
    "build_recording_manifest",
    "build_overlay_spec",
    "build_screenshot_artifact_bundle",
    "build_screenshot_sidecar",
    "validate_overlay_spec",
    "evaluate_recording_budget",
    "toggle_overlay_non_destructive",
    "screenshot_artifacts_are_atomic",
    "default_debug_capture_platform_specs",
    "debug_capture_platform_capability_matrix",
    "build_debug_capability_registry",
    "default_debug_menu_adapter_specs",
    "debug_menu_adapter_capability_matrix",
    "validate_debug_menu_actions",
    "FrameRateController",
    "Engine",
    "FullRewrite",
    "HDIEvent",
    "HDIEventSource",
    "HDIThread",
    "InputEvent",
    "Multiply",
    "PushColumn",
    "PushRow",
    "ShiftFrame",
    "ReplaceRect",
    "ReplaceColumn",
    "ReplaceRow",
    "RenderTick",
    "SceneRenderTick",
    "SceneBlitEvent",
    "SceneFrame",
    "SceneGraphBuffer",
    "SceneTelemetry",
    "ClearNode",
    "ShaderRectNode",
    "RectNode",
    "CircleNode",
    "TextNode",
    "ImageNode",
    "SvgNode",
    "CpuLayerNode",
    "MatrixUIFrameRenderer",
    "CoordinateFrame",
    "CoordinateFrameRegistry",
    "PRESET_SCREEN_TL",
    "PRESET_CARTESIAN_BL",
    "PRESET_CARTESIAN_CENTER",
    "EnergySafetyController",
    "EnergySafetyDecision",
    "EnergySafetyPolicy",
    "SensorEnergySafetyController",
    "DEFAULT_ENABLED_SENSORS",
    "CURRENT_PROTOCOL_VERSION",
    "DEPRECATED_PROTOCOL_VERSIONS",
    "SUPPORTED_PROTOCOL_VERSIONS",
    "ProtocolCompatibility",
    "check_protocol_compatibility",
    "FallbackSensorProvider",
    "SensorReadDeniedError",
    "SensorReadUnavailableError",
    "SensorManagerThread",
    "SensorProvider",
    "SensorSample",
    "TTLCachedSensorProvider",
    "SQLiteAuditSink",
    "UnifiedRunResult",
    "UnifiedRuntime",
    "WriteBatch",
    "WindowMatrix",
]

_MODULE_MAP: dict[str, str] = {
    "JsonlAuditSink": ".audit",
    "SQLiteAuditSink": ".audit",
    "APP_PROTOCOL_VERSION": ".app_runtime",
    "AppDebugPolicy": ".app_runtime",
    "AppContext": ".app_runtime",
    "AppLifecycle": ".app_runtime",
    "AppManifest": ".app_runtime",
    "AppRuntime": ".app_runtime",
    "AppUIRenderer": ".app_runtime",
    "AppVariant": ".app_runtime",
    "ResolvedAppVariant": ".app_runtime",
    "DisplayRuntime": ".display_runtime",
    "RenderTick": ".display_runtime",
    "SceneRenderTick": ".scene_display_runtime",
    "SceneBlitEvent": ".scene_graph",
    "SceneFrame": ".scene_graph",
    "SceneGraphBuffer": ".scene_graph",
    "SceneTelemetry": ".scene_graph",
    "ClearNode": ".scene_graph",
    "ShaderRectNode": ".scene_graph",
    "RectNode": ".scene_graph",
    "CircleNode": ".scene_graph",
    "TextNode": ".scene_graph",
    "ImageNode": ".scene_graph",
    "SvgNode": ".scene_graph",
    "CpuLayerNode": ".scene_graph",
    "DEFAULT_DEBUG_MENU_ACTIONS": ".debug_menu",
    "DebugMenuAdapterSpec": ".debug_menu",
    "DebugMenuActionSpec": ".debug_menu",
    "DebugMenuDispatchResult": ".debug_menu",
    "DebugMenuDispatcher": ".debug_menu",
    "build_debug_capability_registry": ".debug_menu",
    "debug_menu_adapter_capability_matrix": ".debug_menu",
    "default_debug_menu_adapter_specs": ".debug_menu",
    "validate_debug_menu_actions": ".debug_menu",
    "OverlayRect": ".debug_capture",
    "OverlaySpec": ".debug_capture",
    "OverlayToggleResult": ".debug_capture",
    "REQUIRED_SCREENSHOT_SIDECAR_KEYS": ".debug_capture",
    "REQUIRED_RECORDING_MANIFEST_KEYS": ".debug_capture",
    "DebugCapturePlatformSpec": ".debug_capture",
    "RecordingBudgetEnvelope": ".debug_capture",
    "RecordingBudgetResult": ".debug_capture",
    "ScreenshotArtifactBundle": ".debug_capture",
    "build_recording_manifest": ".debug_capture",
    "build_screenshot_artifact_bundle": ".debug_capture",
    "build_screenshot_sidecar": ".debug_capture",
    "build_overlay_spec": ".debug_capture",
    "evaluate_recording_budget": ".debug_capture",
    "default_debug_capture_platform_specs": ".debug_capture",
    "screenshot_artifacts_are_atomic": ".debug_capture",
    "toggle_overlay_non_destructive": ".debug_capture",
    "validate_overlay_spec": ".debug_capture",
    "debug_capture_platform_capability_matrix": ".debug_capture",
    "FrameRateController": ".frame_rate_controller",
    "MatrixUIFrameRenderer": ".ui_frame_renderer",
    "CoordinateFrame": ".coordinates",
    "CoordinateFrameRegistry": ".coordinates",
    "PRESET_CARTESIAN_BL": ".coordinates",
    "PRESET_CARTESIAN_CENTER": ".coordinates",
    "PRESET_SCREEN_TL": ".coordinates",
    "EnergySafetyController": ".energy_safety",
    "EnergySafetyDecision": ".energy_safety",
    "EnergySafetyPolicy": ".energy_safety",
    "SensorEnergySafetyController": ".energy_safety",
    "Engine": ".engine",
    "HDIEvent": ".hdi_thread",
    "HDIEventSource": ".hdi_thread",
    "HDIThread": ".hdi_thread",
    "InputEvent": ".events",
    "CURRENT_PROTOCOL_VERSION": ".protocol_governance",
    "DEPRECATED_PROTOCOL_VERSIONS": ".protocol_governance",
    "SUPPORTED_PROTOCOL_VERSIONS": ".protocol_governance",
    "ProtocolCompatibility": ".protocol_governance",
    "check_protocol_compatibility": ".protocol_governance",
    "DEFAULT_ENABLED_SENSORS": ".sensor_manager",
    "FallbackSensorProvider": ".sensor_manager",
    "SensorReadDeniedError": ".sensor_manager",
    "SensorReadUnavailableError": ".sensor_manager",
    "SensorManagerThread": ".sensor_manager",
    "SensorProvider": ".sensor_manager",
    "SensorSample": ".sensor_manager",
    "TTLCachedSensorProvider": ".sensor_manager",
    "UnifiedRunResult": ".unified_runtime",
    "UnifiedRuntime": ".unified_runtime",
    "CallBlitEvent": ".window_matrix",
    "FullRewrite": ".window_matrix",
    "Multiply": ".window_matrix",
    "PushColumn": ".window_matrix",
    "PushRow": ".window_matrix",
    "ShiftFrame": ".window_matrix",
    "ReplaceRect": ".window_matrix",
    "ReplaceColumn": ".window_matrix",
    "ReplaceRow": ".window_matrix",
    "WriteBatch": ".window_matrix",
    "WindowMatrix": ".window_matrix",
}


def __getattr__(name: str):  # noqa: N807
    module_path = _MODULE_MAP.get(name)
    if module_path is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    import importlib
    mod = importlib.import_module(module_path, __name__)
    obj = getattr(mod, name)
    globals()[name] = obj
    return obj
